/**
 * Source-of-truth career library data for the 72 classes the ML model predicts.
 *
 * The `name` of every entry is the EXACT label emitted by the career label
 * encoder (ai/models/career_label_encoder.h5). The seed script derives each
 * career `code` from this name with the same slug rule the frontend uses, so
 * predicted careers link cleanly to their stored profile.
 *
 * Salary figures are indicative USD annual bands [entry, median, senior].
 * Course links use provider search URLs so they always resolve.
 */

const COURSE_BASES = {
  Coursera: 'https://www.coursera.org/search?query=',
  edX: 'https://www.edx.org/search?q=',
  Udemy: 'https://www.udemy.com/courses/search/?q=',
  Khan: 'https://www.khanacademy.org/search?page_search_query=',
}

/** Build a course link from a title, provider and search query. */
function course(title, provider, query) {
  const base = COURSE_BASES[provider] || COURSE_BASES.Coursera
  return { title, provider, url: base + encodeURIComponent(query) }
}

// Intelligence vocabulary aligned with the frontend radar/insight labels.
const INTEL = {
  ling: 'Linguistic',
  logic: 'Logical-Mathematical',
  spatial: 'Spatial',
  body: 'Bodily-Kinesthetic',
  music: 'Musical',
  inter: 'Interpersonal',
  intra: 'Intrapersonal',
  nature: 'Naturalistic',
}

const careers = [
  {
    name: 'Actor / Actress',
    summary: 'Performs characters on stage, film or television to tell stories and move audiences.',
    description: 'Actors interpret scripts, embody characters and deliver performances across theatre, film, television and voice work, often through auditions and long rehearsal cycles.',
    outlook: 'Competitive, project-based demand',
    workEnvironment: 'Stages, film sets, studios; irregular hours and frequent auditions.',
    salary: [30000, 58000, 120000],
    intelligences: [INTEL.body, INTEL.inter, INTEL.ling],
    skills: ['Performance', 'Improvisation', 'Voice and movement', 'Script analysis', 'Emotional range'],
    responsibilities: ['Audition for and rehearse roles', 'Memorize and interpret scripts', 'Collaborate with directors and cast', 'Perform live or on camera'],
    degrees: ["Bachelor's in Theatre, Drama or Performing Arts"],
    certifications: ['Conservatory / acting studio training'],
    courses: [course('Acting & Performance Foundations', 'Coursera', 'acting'), course('Improvisation for Performers', 'Udemy', 'improvisation acting')],
  },
  {
    name: 'Actuary',
    summary: 'Uses mathematics, statistics and financial theory to measure and price risk.',
    description: 'Actuaries model uncertain future events for insurers, pension funds and banks, quantifying risk and setting premiums or reserves.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Insurance and consulting offices; analytical, deadline-driven teams.',
    salary: [70000, 115000, 190000],
    intelligences: [INTEL.logic, INTEL.intra, INTEL.ling],
    skills: ['Probability & statistics', 'Financial modeling', 'Risk analysis', 'Programming (R/Python)', 'Communication'],
    responsibilities: ['Build statistical risk models', 'Price insurance and pension products', 'Analyze loss and mortality data', 'Report findings to stakeholders'],
    degrees: ["Bachelor's in Actuarial Science, Mathematics or Statistics"],
    certifications: ['SOA / CAS actuarial exams', 'Fellowship (FSA/FCAS)'],
    courses: [course('Actuarial Science Foundations', 'edX', 'actuarial science'), course('Probability & Statistics', 'Coursera', 'probability statistics')],
  },
  {
    name: 'Anthropologist',
    summary: 'Studies human societies, cultures and their development across time and place.',
    description: 'Anthropologists conduct fieldwork and comparative research into human behavior, culture, language and biology to understand how communities live and change.',
    outlook: 'Stable demand',
    workEnvironment: 'Universities, museums, field sites and research institutes.',
    salary: [45000, 66000, 100000],
    intelligences: [INTEL.inter, INTEL.ling, INTEL.intra],
    skills: ['Ethnographic research', 'Qualitative analysis', 'Cross-cultural awareness', 'Academic writing', 'Interviewing'],
    responsibilities: ['Conduct field studies and interviews', 'Analyze cultural and social data', 'Publish research findings', 'Advise on cultural and policy matters'],
    degrees: ["Master's or PhD in Anthropology"],
    certifications: ['Field research methods training'],
    courses: [course('Introduction to Anthropology', 'edX', 'anthropology'), course('Qualitative Research Methods', 'Coursera', 'qualitative research')],
  },
  {
    name: 'Archeologist',
    summary: 'Recovers and interprets material remains to reconstruct past human life.',
    description: 'Archeologists excavate, document and analyze artifacts and sites to understand historic and prehistoric cultures.',
    outlook: 'Stable demand',
    workEnvironment: 'Excavation sites, labs, universities and heritage agencies.',
    salary: [42000, 63000, 95000],
    intelligences: [INTEL.spatial, INTEL.logic, INTEL.nature],
    skills: ['Excavation techniques', 'Artifact analysis', 'Mapping & GIS', 'Research', 'Documentation'],
    responsibilities: ['Survey and excavate sites', 'Catalog and preserve artifacts', 'Analyze and date findings', 'Publish site reports'],
    degrees: ["Master's in Archaeology or Anthropology"],
    certifications: ['Field school certification'],
    courses: [course('Archaeology Foundations', 'Coursera', 'archaeology'), course('GIS for Fieldwork', 'Udemy', 'GIS mapping')],
  },
  {
    name: 'Artist',
    summary: 'Creates original visual works to express ideas, emotion and aesthetics.',
    description: 'Artists produce paintings, sculptures, illustrations and mixed-media work, developing a personal style and often exhibiting or selling their work.',
    outlook: 'Project-based demand',
    workEnvironment: 'Studios, galleries and freelance settings.',
    salary: [30000, 52000, 95000],
    intelligences: [INTEL.spatial, INTEL.body, INTEL.intra],
    skills: ['Drawing & painting', 'Composition', 'Color theory', 'Creativity', 'Portfolio building'],
    responsibilities: ['Conceive and create original works', 'Develop a distinctive style', 'Exhibit and market artwork', 'Manage commissions'],
    degrees: ["Bachelor's in Fine Arts or equivalent portfolio"],
    certifications: ['Atelier / studio training'],
    courses: [course('Fundamentals of Drawing', 'Udemy', 'drawing fundamentals'), course('Modern Art & Ideas', 'Coursera', 'modern art')],
  },
  {
    name: 'Astronomer',
    summary: 'Studies celestial objects and the physics of the universe.',
    description: 'Astronomers observe and model stars, planets and galaxies using telescopes and data analysis to advance our understanding of the cosmos.',
    outlook: 'Steady research demand',
    workEnvironment: 'Observatories, universities and research labs.',
    salary: [60000, 105000, 165000],
    intelligences: [INTEL.logic, INTEL.spatial, INTEL.intra],
    skills: ['Astrophysics', 'Data analysis', 'Programming', 'Mathematical modeling', 'Scientific writing'],
    responsibilities: ['Observe and record celestial phenomena', 'Analyze astronomical data', 'Develop and test theoretical models', 'Publish peer-reviewed research'],
    degrees: ['PhD in Astronomy or Astrophysics'],
    certifications: ['Research fellowships'],
    courses: [course('Astrophysics Fundamentals', 'edX', 'astrophysics'), course('Data Science for Astronomy', 'Coursera', 'data analysis python')],
  },
  {
    name: 'Athlete',
    summary: 'Competes in sport at a professional or elite level.',
    description: 'Athletes train intensively to compete in their discipline, balancing physical conditioning, technique, strategy and recovery.',
    outlook: 'Highly competitive',
    workEnvironment: 'Training facilities, arenas and travel for competition.',
    salary: [35000, 70000, 250000],
    intelligences: [INTEL.body, INTEL.intra, INTEL.inter],
    skills: ['Physical conditioning', 'Discipline', 'Strategy', 'Teamwork', 'Resilience'],
    responsibilities: ['Train and condition daily', 'Compete in events', 'Follow nutrition and recovery plans', 'Work with coaches and analysts'],
    degrees: ['Sport-specific development pathway'],
    certifications: ['Sports / fitness certifications'],
    courses: [course('Sports Performance Science', 'Coursera', 'sports science'), course('Strength & Conditioning', 'Udemy', 'strength conditioning')],
  },
  {
    name: 'Audiologist',
    summary: 'Diagnoses and treats hearing and balance disorders.',
    description: 'Audiologists assess hearing, fit hearing aids and rehabilitate patients with auditory and vestibular conditions.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Clinics, hospitals and ENT practices.',
    salary: [62000, 84000, 115000],
    intelligences: [INTEL.inter, INTEL.logic, INTEL.intra],
    skills: ['Audiometry', 'Patient assessment', 'Hearing-aid fitting', 'Empathy', 'Clinical documentation'],
    responsibilities: ['Test hearing and balance', 'Diagnose auditory disorders', 'Fit and tune hearing devices', 'Counsel patients and families'],
    degrees: ['Doctor of Audiology (AuD)'],
    certifications: ['State licensure', 'CCC-A certification'],
    courses: [course('Introduction to Audiology', 'Coursera', 'audiology'), course('Anatomy of Hearing', 'edX', 'hearing anatomy')],
  },
  {
    name: 'Banking',
    summary: 'Manages financial services, accounts and lending for clients and institutions.',
    description: 'Banking professionals handle deposits, loans, credit and financial advice across retail, commercial and investment functions.',
    outlook: 'Stable demand',
    workEnvironment: 'Bank branches, corporate offices and trading floors.',
    salary: [45000, 72000, 140000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['Financial analysis', 'Customer service', 'Credit assessment', 'Compliance', 'Negotiation'],
    responsibilities: ['Manage customer accounts and loans', 'Assess credit and risk', 'Advise clients on products', 'Ensure regulatory compliance'],
    degrees: ["Bachelor's in Finance, Economics or Commerce"],
    certifications: ['CFA (optional)', 'Banking compliance certifications'],
    courses: [course('Introduction to Banking & Finance', 'Coursera', 'banking finance'), course('Financial Markets', 'edX', 'financial markets')],
  },
  {
    name: 'Broadcaster',
    summary: 'Presents news, sports or entertainment on radio, television or streaming.',
    description: 'Broadcasters research, present and anchor programming, communicating clearly and engagingly to live and recorded audiences.',
    outlook: 'Stable demand',
    workEnvironment: 'Studios, newsrooms and live event locations.',
    salary: [35000, 58000, 110000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.intra],
    skills: ['Public speaking', 'Voice control', 'Research', 'Improvisation', 'Storytelling'],
    responsibilities: ['Present live and recorded segments', 'Research and prepare scripts', 'Interview guests', 'Engage with the audience'],
    degrees: ["Bachelor's in Journalism, Communications or Media"],
    certifications: ['Broadcast media training'],
    courses: [course('Broadcast Journalism', 'Udemy', 'broadcast journalism'), course('Public Speaking', 'Coursera', 'public speaking')],
  },
  {
    name: 'Business Analyst',
    summary: 'Bridges business needs and technical solutions through analysis and requirements.',
    description: 'Business analysts study processes, gather requirements and recommend improvements that align operations with strategy and technology.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Corporate offices, agile teams, hybrid-friendly.',
    salary: [60000, 85000, 125000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['Requirements gathering', 'Process modeling', 'Data analysis', 'Stakeholder management', 'Documentation'],
    responsibilities: ['Elicit and document requirements', 'Map and improve processes', 'Analyze operational data', 'Coordinate stakeholders and developers'],
    degrees: ["Bachelor's in Business, IT or related field"],
    certifications: ['CBAP', 'Agile / Scrum certifications'],
    courses: [course('Business Analysis Fundamentals', 'Udemy', 'business analysis'), course('Agile with Atlassian Jira', 'Coursera', 'agile scrum')],
  },
  {
    name: 'Business manager',
    summary: 'Coordinates operations, projects and people to achieve organizational targets.',
    description: 'Business managers plan budgets, lead teams and oversee performance to keep a department or company on track toward its goals.',
    outlook: 'Stable demand',
    workEnvironment: 'Corporate offices, client boardrooms, team environments.',
    salary: [70000, 105000, 160000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['Strategic planning', 'Financial analysis', 'Team leadership', 'Negotiation', 'Conflict resolution'],
    responsibilities: ['Set team goals and budgets', 'Analyze operational performance', 'Manage staffing and workflows', 'Report progress to executives'],
    degrees: ["Bachelor's in Business Administration (BBA) or MBA"],
    certifications: ['PMP', 'Leadership programs'],
    courses: [course('Business Management Foundations', 'Coursera', 'business management'), course('Leadership & Team Management', 'Udemy', 'leadership management')],
  },
  {
    name: 'Chartered Accountant',
    summary: 'Provides expert accounting, audit and tax services to organizations.',
    description: 'Chartered accountants prepare and audit financial statements, advise on tax and ensure compliance with accounting standards.',
    outlook: 'Strong demand',
    workEnvironment: 'Accounting firms and corporate finance departments.',
    salary: [55000, 90000, 160000],
    intelligences: [INTEL.logic, INTEL.intra, INTEL.ling],
    skills: ['Financial reporting', 'Auditing', 'Taxation', 'Compliance', 'Analytical reasoning'],
    responsibilities: ['Prepare and audit financial statements', 'Advise on tax planning', 'Ensure regulatory compliance', 'Analyze financial performance'],
    degrees: ["Bachelor's in Accounting or Commerce"],
    certifications: ['CA / ACCA / CPA qualification'],
    courses: [course('Financial Accounting Fundamentals', 'Coursera', 'financial accounting'), course('Auditing Principles', 'edX', 'auditing')],
  },
  {
    name: 'Chief financial officer',
    summary: 'Leads an organization’s financial strategy, planning and reporting.',
    description: 'CFOs oversee finance functions, manage capital and risk, and guide executive decisions with financial insight.',
    outlook: 'Senior, competitive',
    workEnvironment: 'Executive offices; board and investor engagement.',
    salary: [150000, 260000, 450000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.intra],
    skills: ['Financial strategy', 'Capital management', 'Risk governance', 'Leadership', 'Investor relations'],
    responsibilities: ['Set financial strategy and budgets', 'Manage capital structure and risk', 'Report to board and investors', 'Lead the finance organization'],
    degrees: ['MBA or Master’s in Finance'],
    certifications: ['CPA', 'CFA'],
    courses: [course('Corporate Finance', 'Coursera', 'corporate finance'), course('Financial Leadership', 'edX', 'financial management')],
  },
  {
    name: 'Company secretary',
    summary: 'Ensures corporate governance, compliance and board administration.',
    description: 'Company secretaries manage statutory compliance, board meetings and records, advising directors on governance obligations.',
    outlook: 'Stable demand',
    workEnvironment: 'Corporate governance and legal departments.',
    salary: [50000, 78000, 130000],
    intelligences: [INTEL.logic, INTEL.ling, INTEL.intra],
    skills: ['Corporate law', 'Governance', 'Compliance', 'Minute taking', 'Attention to detail'],
    responsibilities: ['Administer board meetings and records', 'Ensure statutory compliance', 'Advise on governance', 'Maintain corporate filings'],
    degrees: ["Bachelor's in Law, Commerce or Company Secretaryship"],
    certifications: ['CS / ICSA qualification'],
    courses: [course('Corporate Governance', 'Coursera', 'corporate governance'), course('Business Law Basics', 'edX', 'business law')],
  },
  {
    name: 'Computer analyst',
    summary: 'Analyzes information systems and processes to recommend technical improvements.',
    description: 'Computer (systems) analysts study IT systems and business needs, designing and coordinating solutions that improve efficiency.',
    outlook: 'Growing demand',
    workEnvironment: 'Consulting agencies, corporate IT offices, stakeholder meetings.',
    salary: [65000, 92000, 130000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['System analysis', 'Requirement gathering', 'UML modeling', 'Agile methodologies', 'Business analysis'],
    responsibilities: ['Analyze IT systems and process flows', 'Document requirements for developers', 'Coordinate stakeholders and engineers', 'Plan system integrations and migrations'],
    degrees: ["Bachelor's in Computer Information Systems or related field"],
    certifications: ['ITIL', 'Agile / Scrum certifications'],
    courses: [course('Systems Analysis & Design', 'Udemy', 'systems analysis design'), course('IT Business Analysis', 'Coursera', 'IT business analysis')],
  },
  {
    name: 'Computer programmer',
    summary: 'Writes, tests and debugs code to build software applications.',
    description: 'Computer programmers translate designs into working software, building and maintaining applications and aligning with logical, structured problem-solving.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Collaborative teams, hybrid or remote-friendly.',
    salary: [70000, 105000, 160000],
    intelligences: [INTEL.logic, INTEL.spatial, INTEL.ling],
    skills: ['Algorithm design', 'Systems thinking', 'Version control', 'Debugging', 'Technical communication'],
    responsibilities: ['Design and implement software features', 'Collaborate on requirements and specifications', 'Review code and maintain quality', 'Document design and architectural decisions'],
    degrees: ["Bachelor's in Computer Science or Software Engineering"],
    certifications: ['Cloud / language certifications (optional)'],
    courses: [course('Python for Everybody', 'Coursera', 'python programming'), course('Data Structures & Algorithms', 'edX', 'data structures algorithms')],
  },
  {
    name: 'Consultant',
    summary: 'Advises organizations on strategy, operations and problem-solving.',
    description: 'Consultants analyze client challenges and deliver recommendations that improve performance, drawing on structured frameworks and communication.',
    outlook: 'Strong demand',
    workEnvironment: 'Client sites, consulting firms; frequent travel.',
    salary: [70000, 110000, 200000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['Problem structuring', 'Data analysis', 'Presentation', 'Stakeholder management', 'Strategy'],
    responsibilities: ['Diagnose client problems', 'Analyze data and benchmarks', 'Develop recommendations', 'Present and implement solutions'],
    degrees: ["Bachelor's or MBA in Business or relevant field"],
    certifications: ['Domain certifications (varies)'],
    courses: [course('Management Consulting', 'Udemy', 'management consulting'), course('Strategic Management', 'Coursera', 'strategy')],
  },
  {
    name: 'Counselor',
    summary: 'Helps clients navigate emotional, mental and developmental challenges.',
    description: 'Counselors provide guidance and therapeutic support, using empathy, active listening and structured interventions to help clients cope and grow.',
    outlook: 'Strong growth',
    workEnvironment: 'Schools, community centers, rehabilitation facilities.',
    salary: [42000, 58000, 85000],
    intelligences: [INTEL.inter, INTEL.intra, INTEL.ling],
    skills: ['Active listening', 'Crisis intervention', 'Group therapy', 'Empathy', 'Case management'],
    responsibilities: ['Assess clients during intake', 'Conduct counseling sessions', 'Set therapeutic recovery goals', 'Coordinate care with specialists'],
    degrees: ["Master's in Counseling or related field"],
    certifications: ['State counseling license', 'LPC / LMFT'],
    courses: [course('Foundations of Counseling', 'Coursera', 'counseling psychology'), course('Positive Psychology', 'edX', 'positive psychology')],
  },
  {
    name: 'Criminologist',
    summary: 'Studies crime, criminal behavior and the justice system.',
    description: 'Criminologists analyze patterns of crime and the social and psychological factors behind it to inform policy and prevention.',
    outlook: 'Stable demand',
    workEnvironment: 'Research institutes, government and universities.',
    salary: [45000, 68000, 100000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['Research methods', 'Statistical analysis', 'Criminal psychology', 'Report writing', 'Critical thinking'],
    responsibilities: ['Analyze crime data and trends', 'Research causes of criminal behavior', 'Advise on prevention and policy', 'Publish findings'],
    degrees: ["Master's in Criminology or Sociology"],
    certifications: ['Research methods training'],
    courses: [course('Introduction to Criminology', 'edX', 'criminology'), course('Crime Data Analysis', 'Coursera', 'data analysis')],
  },
  {
    name: 'Dancer',
    summary: 'Expresses ideas and emotion through choreographed movement and performance.',
    description: 'Dancers train and perform across genres, combining physical discipline, musicality and artistic expression on stage and screen.',
    outlook: 'Competitive, project-based',
    workEnvironment: 'Studios, theatres and touring productions.',
    salary: [28000, 48000, 90000],
    intelligences: [INTEL.body, INTEL.music, INTEL.intra],
    skills: ['Technique', 'Choreography', 'Musicality', 'Stamina', 'Performance'],
    responsibilities: ['Train and rehearse daily', 'Learn and perform choreography', 'Audition for productions', 'Maintain physical conditioning'],
    degrees: ["Bachelor's in Dance or conservatory training"],
    certifications: ['Dance teaching certifications'],
    courses: [course('Dance Fundamentals', 'Udemy', 'dance technique'), course('Choreography Basics', 'Coursera', 'choreography')],
  },
  {
    name: 'Database designer',
    summary: 'Designs, implements and maintains database systems that organize and secure data.',
    description: 'Database designers model relational and non-relational schemas, optimize queries and ensure data integrity and security.',
    outlook: 'High demand',
    workEnvironment: 'Database administration units, security audits, remote-friendly.',
    salary: [75000, 105000, 150000],
    intelligences: [INTEL.logic, INTEL.spatial, INTEL.intra],
    skills: ['SQL', 'Data modeling', 'Query optimization', 'Performance tuning', 'Information security'],
    responsibilities: ['Design logical and physical data models', 'Ensure data integrity and security', 'Optimize complex queries', 'Plan backup and recovery'],
    degrees: ["Bachelor's in Information Technology or Computer Science"],
    certifications: ['Oracle / Microsoft DBA certifications'],
    courses: [course('Database Design & SQL', 'Coursera', 'database design sql'), course('Relational Databases', 'edX', 'relational databases')],
  },
  {
    name: 'Economist',
    summary: 'Studies the production, distribution and consumption of resources.',
    description: 'Economists analyze data and trends to explain economic behavior and advise on policy, markets and forecasting.',
    outlook: 'Strong demand',
    workEnvironment: 'Government, research institutes, banks and academia.',
    salary: [65000, 105000, 170000],
    intelligences: [INTEL.logic, INTEL.ling, INTEL.intra],
    skills: ['Econometrics', 'Statistical modeling', 'Data analysis', 'Forecasting', 'Policy analysis'],
    responsibilities: ['Collect and analyze economic data', 'Build forecasting models', 'Advise on policy and markets', 'Publish reports and research'],
    degrees: ["Master's or PhD in Economics"],
    certifications: ['Econometrics / data certifications'],
    courses: [course('Principles of Economics', 'edX', 'economics'), course('Econometrics', 'Coursera', 'econometrics')],
  },
  {
    name: 'Editor',
    summary: 'Shapes and refines written content for clarity, accuracy and style.',
    description: 'Editors review and revise manuscripts and copy, guiding tone, structure and accuracy across publishing and media.',
    outlook: 'Stable demand',
    workEnvironment: 'Publishing houses, media outlets, remote-friendly.',
    salary: [42000, 62000, 95000],
    intelligences: [INTEL.ling, INTEL.intra, INTEL.logic],
    skills: ['Copy editing', 'Proofreading', 'Style guides', 'Content structure', 'Attention to detail'],
    responsibilities: ['Edit manuscripts and copy', 'Ensure accuracy and consistency', 'Coach writers on style', 'Manage editorial timelines'],
    degrees: ["Bachelor's in English, Journalism or Communications"],
    certifications: ['Editing / proofreading certificates'],
    courses: [course('Editing & Proofreading', 'Udemy', 'editing proofreading'), course('English Composition', 'Coursera', 'english writing')],
  },
  {
    name: 'Engineer',
    summary: 'Applies scientific and mathematical principles to design structures, machines or systems.',
    description: 'Engineers design, build and test physical and mechanical systems, combining spatial visualization, mathematics and hands-on precision.',
    outlook: 'Stable demand',
    workEnvironment: 'Design studios, construction sites, manufacturing labs.',
    salary: [65000, 95000, 140000],
    intelligences: [INTEL.logic, INTEL.spatial, INTEL.body],
    skills: ['CAD software', 'Material science', 'Prototyping', 'Mathematical modeling', 'Safety codes'],
    responsibilities: ['Perform structural and material calculations', 'Create models and engineering drawings', 'Prototype and test components', 'Coordinate specifications on-site'],
    degrees: ["Bachelor's in Engineering"],
    certifications: ['Professional Engineer (PE) license'],
    courses: [course('Engineering Mechanics', 'edX', 'engineering mechanics'), course('CAD for Engineers', 'Udemy', 'CAD design')],
  },
  {
    name: 'Fashion Designer',
    summary: 'Designs clothing and accessories blending aesthetics, function and trends.',
    description: 'Fashion designers sketch, source materials and oversee garment creation, translating concepts and trends into wearable collections.',
    outlook: 'Competitive demand',
    workEnvironment: 'Design studios, ateliers and showrooms.',
    salary: [40000, 65000, 120000],
    intelligences: [INTEL.spatial, INTEL.body, INTEL.intra],
    skills: ['Sketching', 'Textile knowledge', 'Pattern making', 'Trend analysis', 'Color & composition'],
    responsibilities: ['Design garments and accessories', 'Select fabrics and materials', 'Oversee prototyping and production', 'Present seasonal collections'],
    degrees: ["Bachelor's in Fashion Design"],
    certifications: ['Portfolio / atelier training'],
    courses: [course('Fashion Design Fundamentals', 'Udemy', 'fashion design'), course('Fashion as Design', 'Coursera', 'fashion design')],
  },
  {
    name: 'Financial Advisor',
    summary: 'Guides clients on investments, savings and financial planning.',
    description: 'Financial advisors assess clients’ goals and risk, then recommend investment, retirement and insurance strategies.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Advisory firms, banks; client-facing.',
    salary: [50000, 88000, 160000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.ling],
    skills: ['Financial planning', 'Investment analysis', 'Client relationship', 'Risk profiling', 'Communication'],
    responsibilities: ['Assess client goals and risk', 'Recommend financial products', 'Build and review portfolios', 'Maintain client relationships'],
    degrees: ["Bachelor's in Finance, Economics or Business"],
    certifications: ['CFP', 'Series 7 / licensing'],
    courses: [course('Personal & Family Financial Planning', 'Coursera', 'financial planning'), course('Investment Management', 'edX', 'investment management')],
  },
  {
    name: 'Geologist',
    summary: 'Studies the Earth’s materials, processes and history.',
    description: 'Geologists examine rocks, minerals and landforms to understand Earth processes and locate natural resources.',
    outlook: 'Stable demand',
    workEnvironment: 'Field sites, labs, energy and mining companies.',
    salary: [55000, 85000, 135000],
    intelligences: [INTEL.nature, INTEL.logic, INTEL.spatial],
    skills: ['Field mapping', 'Mineralogy', 'Data analysis', 'GIS', 'Report writing'],
    responsibilities: ['Conduct geological surveys', 'Analyze rock and soil samples', 'Map subsurface structures', 'Assess resource and hazard risk'],
    degrees: ["Bachelor's or Master's in Geology or Earth Science"],
    certifications: ['Professional Geologist (PG) license'],
    courses: [course('Introduction to Geology', 'Coursera', 'geology'), course('GIS Fundamentals', 'Udemy', 'GIS')],
  },
  {
    name: 'Graphic Designer',
    summary: 'Creates visual concepts to communicate ideas that inform and captivate.',
    description: 'Graphic designers craft layouts, typography and imagery for brands and media, blending spatial visualization with aesthetic judgment.',
    outlook: 'Stable demand',
    workEnvironment: 'Design agencies, marketing teams, freelance settings.',
    salary: [42000, 62000, 95000],
    intelligences: [INTEL.spatial, INTEL.ling, INTEL.body],
    skills: ['Adobe Creative Suite', 'Typography', 'Visual branding', 'Layout & composition', 'Color theory'],
    responsibilities: ['Develop layouts and brand assets', 'Select typography and imagery', 'Present concepts to clients', 'Prepare print- and web-ready files'],
    degrees: ["Bachelor's in Graphic Design or portfolio equivalent"],
    certifications: ['Adobe Certified Professional'],
    courses: [course('Graphic Design Specialization', 'Coursera', 'graphic design'), course('Typography', 'Udemy', 'typography')],
  },
  {
    name: 'Historian',
    summary: 'Researches and interprets the past through documents and evidence.',
    description: 'Historians analyze sources to reconstruct and explain historical events, writing and teaching about their findings.',
    outlook: 'Stable demand',
    workEnvironment: 'Universities, archives and museums.',
    salary: [45000, 66000, 100000],
    intelligences: [INTEL.ling, INTEL.intra, INTEL.logic],
    skills: ['Archival research', 'Source analysis', 'Academic writing', 'Critical thinking', 'Synthesis'],
    responsibilities: ['Research primary and secondary sources', 'Analyze and interpret evidence', 'Write articles and books', 'Teach and present findings'],
    degrees: ["Master's or PhD in History"],
    certifications: ['Archival research training'],
    courses: [course('The Modern World History', 'Coursera', 'world history'), course('Historical Research Methods', 'edX', 'historical research')],
  },
  {
    name: 'Interior Decorator',
    summary: 'Designs functional and aesthetically pleasing interior spaces.',
    description: 'Interior decorators plan layouts, color schemes and furnishings to create comfortable, attractive environments for clients.',
    outlook: 'Stable demand',
    workEnvironment: 'Design studios, client sites and showrooms.',
    salary: [40000, 60000, 100000],
    intelligences: [INTEL.spatial, INTEL.inter, INTEL.body],
    skills: ['Space planning', 'Color & materials', 'Sketching', 'Client consultation', 'Project coordination'],
    responsibilities: ['Plan interior layouts', 'Select colors, furniture and materials', 'Consult with clients on style', 'Coordinate contractors and budgets'],
    degrees: ["Bachelor's or diploma in Interior Design"],
    certifications: ['Interior design certifications'],
    courses: [course('Interior Design Fundamentals', 'Udemy', 'interior design'), course('Color & Space', 'Coursera', 'interior design')],
  },
  {
    name: 'Internal auditor',
    summary: 'Evaluates internal controls, risk and compliance within organizations.',
    description: 'Internal auditors independently review financial and operational processes to ensure controls, accuracy and regulatory compliance.',
    outlook: 'Strong demand',
    workEnvironment: 'Corporate audit and risk departments.',
    salary: [55000, 80000, 125000],
    intelligences: [INTEL.logic, INTEL.intra, INTEL.ling],
    skills: ['Risk assessment', 'Internal controls', 'Auditing', 'Compliance', 'Analytical reasoning'],
    responsibilities: ['Plan and conduct audits', 'Evaluate internal controls', 'Identify and report risks', 'Recommend process improvements'],
    degrees: ["Bachelor's in Accounting, Finance or Business"],
    certifications: ['CIA', 'CPA (optional)'],
    courses: [course('Internal Auditing', 'Coursera', 'internal audit'), course('Risk Management', 'edX', 'risk management')],
  },
  {
    name: 'Journalist',
    summary: 'Researches, writes and reports news and stories for the public.',
    description: 'Journalists investigate, verify and communicate news across print, broadcast and digital media, often under tight deadlines.',
    outlook: 'Evolving demand',
    workEnvironment: 'Newsrooms, field assignments, remote-friendly.',
    salary: [38000, 55000, 95000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.intra],
    skills: ['Investigative research', 'Writing', 'Interviewing', 'Fact-checking', 'Storytelling'],
    responsibilities: ['Research and verify stories', 'Interview sources', 'Write and file reports', 'Meet publishing deadlines'],
    degrees: ["Bachelor's in Journalism or Communications"],
    certifications: ['Media / digital journalism training'],
    courses: [course('Journalism Skills', 'Coursera', 'journalism'), course('Investigative Reporting', 'Udemy', 'investigative journalism')],
  },
  {
    name: 'Language Teacher',
    summary: 'Teaches language skills — reading, writing, speaking and comprehension.',
    description: 'Language teachers plan lessons and guide learners toward fluency, adapting instruction to different levels and goals.',
    outlook: 'Stable demand',
    workEnvironment: 'Schools, language institutes, online platforms.',
    salary: [38000, 52000, 80000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.intra],
    skills: ['Lesson planning', 'Communication', 'Assessment', 'Cultural awareness', 'Patience'],
    responsibilities: ['Plan and deliver lessons', 'Assess learner progress', 'Develop language materials', 'Support diverse learners'],
    degrees: ["Bachelor's in Education, Linguistics or the language"],
    certifications: ['TEFL / TESOL', 'Teaching license'],
    courses: [course('Teaching English (TESOL)', 'Coursera', 'TESOL teaching english'), course('Foundations of Teaching', 'edX', 'teaching')],
  },
  {
    name: 'Lawyer',
    summary: 'Advises and represents clients on legal matters and disputes.',
    description: 'Lawyers interpret law, advise clients, draft documents and advocate in negotiations and court.',
    outlook: 'Stable demand',
    workEnvironment: 'Law firms, corporate legal teams and courts.',
    salary: [65000, 120000, 230000],
    intelligences: [INTEL.ling, INTEL.logic, INTEL.inter],
    skills: ['Legal research', 'Argumentation', 'Drafting', 'Negotiation', 'Critical reasoning'],
    responsibilities: ['Advise clients on legal rights', 'Research and interpret law', 'Draft contracts and filings', 'Represent clients in negotiations and court'],
    degrees: ['Law degree (LLB / JD)'],
    certifications: ['Bar admission / licensure'],
    courses: [course('Introduction to Law', 'edX', 'law'), course('Contract Law', 'Coursera', 'contract law')],
  },
  {
    name: 'Leader',
    summary: 'Guides teams and organizations toward shared goals and vision.',
    description: 'Leaders set direction, inspire people and make decisions that align teams around a common purpose and outcomes.',
    outlook: 'Cross-industry demand',
    workEnvironment: 'Organizations of all kinds; team and stakeholder facing.',
    salary: [70000, 120000, 220000],
    intelligences: [INTEL.inter, INTEL.intra, INTEL.ling],
    skills: ['Vision setting', 'Decision making', 'Communication', 'Motivation', 'Strategic thinking'],
    responsibilities: ['Set vision and direction', 'Make key decisions', 'Develop and motivate teams', 'Drive results and accountability'],
    degrees: ["Bachelor's or MBA (varies by field)"],
    certifications: ['Leadership development programs'],
    courses: [course('Leadership Foundations', 'Coursera', 'leadership'), course('Inspiring Leadership', 'edX', 'leadership')],
  },
  {
    name: 'Librarian',
    summary: 'Organizes information resources and helps people access knowledge.',
    description: 'Librarians curate collections, manage information systems and support research and literacy in libraries and institutions.',
    outlook: 'Stable demand',
    workEnvironment: 'Public, academic and special libraries.',
    salary: [42000, 60000, 90000],
    intelligences: [INTEL.ling, INTEL.logic, INTEL.inter],
    skills: ['Information organization', 'Cataloging', 'Research support', 'Digital systems', 'Customer service'],
    responsibilities: ['Curate and catalog collections', 'Assist patrons with research', 'Manage digital and physical resources', 'Run literacy and outreach programs'],
    degrees: ["Master's in Library & Information Science (MLIS)"],
    certifications: ['Library science certifications'],
    courses: [course('Library & Information Science', 'edX', 'library information science'), course('Metadata & Cataloging', 'Coursera', 'metadata cataloging')],
  },
  {
    name: 'Logistics manager',
    summary: 'Plans and coordinates the movement and storage of goods.',
    description: 'Logistics managers optimize supply chains, manage inventory and coordinate transport to deliver goods efficiently.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Warehouses, distribution centers, corporate offices.',
    salary: [58000, 85000, 130000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.spatial],
    skills: ['Supply chain management', 'Inventory planning', 'Process optimization', 'Coordination', 'Data analysis'],
    responsibilities: ['Plan and optimize supply chains', 'Manage inventory and warehousing', 'Coordinate transport and delivery', 'Analyze logistics performance'],
    degrees: ["Bachelor's in Supply Chain, Logistics or Business"],
    certifications: ['APICS / CSCP certifications'],
    courses: [course('Supply Chain Management', 'Coursera', 'supply chain management'), course('Logistics & Operations', 'edX', 'logistics operations')],
  },
  {
    name: 'Manager',
    summary: 'Plans, organizes and oversees teams and operations to meet objectives.',
    description: 'Managers coordinate people, resources and processes, balancing planning and leadership to achieve team and organizational goals.',
    outlook: 'Stable demand',
    workEnvironment: 'Offices and operational settings; team-facing.',
    salary: [60000, 90000, 145000],
    intelligences: [INTEL.inter, INTEL.logic, INTEL.ling],
    skills: ['Team leadership', 'Planning', 'Delegation', 'Communication', 'Problem solving'],
    responsibilities: ['Plan and assign work', 'Lead and develop teams', 'Monitor performance and budgets', 'Resolve operational issues'],
    degrees: ["Bachelor's in Business or relevant field"],
    certifications: ['PMP', 'Management programs'],
    courses: [course('Management Fundamentals', 'Coursera', 'management'), course('People Management', 'Udemy', 'people management')],
  },
  {
    name: 'Marine Biologist',
    summary: 'Studies marine organisms and ocean ecosystems.',
    description: 'Marine biologists research sea life and habitats, conducting fieldwork and lab analysis to understand and protect ocean ecosystems.',
    outlook: 'Steady research demand',
    workEnvironment: 'Field, boats, labs and research institutions.',
    salary: [45000, 68000, 105000],
    intelligences: [INTEL.nature, INTEL.logic, INTEL.intra],
    skills: ['Field research', 'Marine ecology', 'Data analysis', 'Scientific diving', 'Lab techniques'],
    responsibilities: ['Conduct marine field studies', 'Collect and analyze samples', 'Monitor ecosystems and species', 'Publish research findings'],
    degrees: ["Master's or PhD in Marine Biology"],
    certifications: ['Scientific diving certification'],
    courses: [course('Introduction to Marine Biology', 'edX', 'marine biology'), course('Ocean Ecology', 'Coursera', 'marine ecology')],
  },
  {
    name: 'Marketing',
    summary: 'Promotes products and brands to attract and retain customers.',
    description: 'Marketing professionals research audiences, craft campaigns and measure performance across channels to drive brand growth.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Agencies, in-house teams, hybrid-friendly.',
    salary: [45000, 70000, 130000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.logic],
    skills: ['Market research', 'Content & branding', 'Digital channels', 'Analytics', 'Storytelling'],
    responsibilities: ['Research target audiences', 'Plan and run campaigns', 'Create content and messaging', 'Analyze and optimize performance'],
    degrees: ["Bachelor's in Marketing, Business or Communications"],
    certifications: ['Google / HubSpot marketing certifications'],
    courses: [course('Digital Marketing', 'Coursera', 'digital marketing'), course('Marketing Analytics', 'edX', 'marketing analytics')],
  },
  {
    name: 'Mathematician',
    summary: 'Advances and applies mathematical theory to solve abstract and real problems.',
    description: 'Mathematicians develop theories, models and proofs, applying logic and abstraction across research, industry and academia.',
    outlook: 'Strong demand',
    workEnvironment: 'Universities, research labs and tech/finance firms.',
    salary: [65000, 105000, 160000],
    intelligences: [INTEL.logic, INTEL.intra, INTEL.spatial],
    skills: ['Mathematical reasoning', 'Proof writing', 'Modeling', 'Programming', 'Abstraction'],
    responsibilities: ['Develop mathematical theories and models', 'Prove theorems and conjectures', 'Apply math to real-world problems', 'Publish and present research'],
    degrees: ["Master's or PhD in Mathematics"],
    certifications: ['Research training'],
    courses: [course('Mathematical Thinking', 'Coursera', 'mathematical thinking'), course('Linear Algebra', 'edX', 'linear algebra')],
  },
  {
    name: 'Mechanic',
    summary: 'Inspects, maintains and repairs vehicles and machinery.',
    description: 'Mechanics diagnose faults and service engines and mechanical systems, combining hands-on skill with technical knowledge.',
    outlook: 'Stable demand',
    workEnvironment: 'Workshops, garages and service centers.',
    salary: [35000, 52000, 80000],
    intelligences: [INTEL.body, INTEL.logic, INTEL.spatial],
    skills: ['Diagnostics', 'Mechanical repair', 'Tool handling', 'Problem solving', 'Attention to detail'],
    responsibilities: ['Diagnose mechanical faults', 'Repair and service systems', 'Perform routine maintenance', 'Test and verify repairs'],
    degrees: ['Vocational / technical diploma'],
    certifications: ['ASE certification'],
    courses: [course('Automotive Mechanics', 'Udemy', 'automotive mechanics'), course('Engine Systems', 'edX', 'mechanical engineering')],
  },
  {
    name: 'Medical',
    summary: 'Diagnoses, treats and cares for patients across medical fields.',
    description: 'Medical professionals assess, diagnose and treat illness and injury, providing patient care across hospitals and clinics.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Hospitals, clinics and care facilities.',
    salary: [70000, 130000, 250000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.intra],
    skills: ['Clinical assessment', 'Diagnosis', 'Patient care', 'Medical knowledge', 'Communication'],
    responsibilities: ['Examine and diagnose patients', 'Develop treatment plans', 'Administer or prescribe treatment', 'Monitor patient outcomes'],
    degrees: ['Medical degree (MBBS / MD)'],
    certifications: ['Medical licensure', 'Board certification'],
    courses: [course('Foundations of Medicine', 'edX', 'medicine'), course('Clinical Skills', 'Coursera', 'clinical skills')],
  },
  {
    name: 'Middle, Higher School Teacher and Professors',
    summary: 'Educates students at secondary and higher levels in specialized subjects.',
    description: 'Teachers and professors plan curricula, deliver instruction and assess learning, fostering subject mastery and critical thinking.',
    outlook: 'Stable demand',
    workEnvironment: 'Schools, colleges and universities.',
    salary: [45000, 68000, 120000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.intra],
    skills: ['Subject expertise', 'Lesson planning', 'Assessment', 'Communication', 'Mentoring'],
    responsibilities: ['Plan and deliver lessons', 'Assess and grade students', 'Mentor and support learners', 'Develop curriculum and materials'],
    degrees: ["Master's or PhD (higher ed) / Bachelor's + teaching qualification"],
    certifications: ['Teaching license / B.Ed'],
    courses: [course('Foundations of Teaching for Learning', 'Coursera', 'teaching learning'), course('University Teaching', 'edX', 'university teaching')],
  },
  {
    name: 'Militry',
    summary: 'Serves in the armed forces to defend and protect the nation.',
    description: 'Military personnel train and operate in defense roles, requiring discipline, physical fitness, teamwork and leadership.',
    outlook: 'Steady recruitment',
    workEnvironment: 'Bases, field operations; structured and physically demanding.',
    salary: [35000, 55000, 100000],
    intelligences: [INTEL.body, INTEL.inter, INTEL.intra],
    skills: ['Discipline', 'Physical fitness', 'Teamwork', 'Tactical thinking', 'Leadership'],
    responsibilities: ['Train for operational readiness', 'Execute missions and duties', 'Maintain equipment and fitness', 'Lead and support units'],
    degrees: ['Military academy / service training'],
    certifications: ['Defense service qualifications'],
    courses: [course('Leadership & Discipline', 'Coursera', 'leadership'), course('Physical Fitness Training', 'Udemy', 'fitness training')],
  },
  {
    name: 'Music teacher',
    summary: 'Teaches musical theory, instruments and performance skills.',
    description: 'Music teachers instruct students in theory, technique and performance, nurturing musical ability and expression.',
    outlook: 'Stable demand',
    workEnvironment: 'Schools, music studios and private lessons.',
    salary: [35000, 52000, 85000],
    intelligences: [INTEL.music, INTEL.inter, INTEL.body],
    skills: ['Music theory', 'Instrument proficiency', 'Lesson planning', 'Patience', 'Performance coaching'],
    responsibilities: ['Teach theory and technique', 'Guide instrument practice', 'Prepare students for performances', 'Assess musical progress'],
    degrees: ["Bachelor's in Music or Music Education"],
    certifications: ['Teaching license / music certifications'],
    courses: [course('Fundamentals of Music Theory', 'Coursera', 'music theory'), course('Teaching Music', 'Udemy', 'music teaching')],
  },
  {
    name: 'Nature photographer',
    summary: 'Captures wildlife and landscapes through photography.',
    description: 'Nature photographers document the natural world, combining technical camera skills with patience and an eye for composition.',
    outlook: 'Competitive, freelance',
    workEnvironment: 'Outdoors, remote locations and studios.',
    salary: [30000, 50000, 95000],
    intelligences: [INTEL.spatial, INTEL.nature, INTEL.intra],
    skills: ['Photography technique', 'Composition', 'Photo editing', 'Patience', 'Field craft'],
    responsibilities: ['Plan and scout shoots', 'Capture wildlife and landscapes', 'Edit and process images', 'License and sell photography'],
    degrees: ['Photography diploma or portfolio'],
    certifications: ['Photography workshops'],
    courses: [course('Photography Basics', 'Coursera', 'photography'), course('Nature & Wildlife Photography', 'Udemy', 'wildlife photography')],
  },
  {
    name: 'Para Medical (physiotherapy, occupational theropy, audio and speech language theropy, nursing)',
    summary: 'Provides allied health care — therapy, rehabilitation and nursing support.',
    description: 'Paramedical professionals deliver physiotherapy, occupational, speech-language therapy and nursing, supporting diagnosis, treatment and rehabilitation.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Hospitals, clinics, rehab centers and home care.',
    salary: [40000, 62000, 95000],
    intelligences: [INTEL.inter, INTEL.body, INTEL.intra],
    skills: ['Patient care', 'Rehabilitation techniques', 'Clinical assessment', 'Empathy', 'Communication'],
    responsibilities: ['Assess patient needs', 'Deliver therapy and care', 'Track recovery progress', 'Educate patients and families'],
    degrees: ["Bachelor's in Physiotherapy, Nursing or allied health"],
    certifications: ['Allied health licensure / registration'],
    courses: [course('Foundations of Physiotherapy', 'edX', 'physiotherapy'), course('Vital Signs & Patient Care', 'Coursera', 'nursing patient care')],
  },
  {
    name: 'Para Militry (https://en.wikipedia.org/wiki/Paramilitary_forces_of_India)',
    summary: 'Serves in paramilitary forces for internal security and border protection.',
    description: 'Paramilitary personnel support national security through border guarding, internal security and disaster response, requiring fitness and discipline.',
    outlook: 'Steady recruitment',
    workEnvironment: 'Field deployments, borders and security operations.',
    salary: [32000, 50000, 90000],
    intelligences: [INTEL.body, INTEL.inter, INTEL.intra],
    skills: ['Physical fitness', 'Discipline', 'Tactical awareness', 'Teamwork', 'Resilience'],
    responsibilities: ['Maintain security and order', 'Patrol and guard assignments', 'Respond to emergencies', 'Support disaster relief'],
    degrees: ['Service training / academy'],
    certifications: ['Paramilitary service qualifications'],
    courses: [course('Security & Safety Fundamentals', 'Udemy', 'security training'), course('Emergency Response', 'Coursera', 'emergency response')],
  },
  {
    name: 'Pharmacist',
    summary: 'Prepares and dispenses medications and advises on their safe use.',
    description: 'Pharmacists dispense prescriptions, counsel patients and ensure safe, effective medication use in clinical and retail settings.',
    outlook: 'Stable demand',
    workEnvironment: 'Pharmacies, hospitals and clinical settings.',
    salary: [85000, 115000, 150000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.intra],
    skills: ['Pharmacology', 'Attention to detail', 'Patient counseling', 'Compliance', 'Communication'],
    responsibilities: ['Dispense and verify medications', 'Counsel patients on use', 'Check for interactions', 'Maintain pharmacy records'],
    degrees: ['Doctor of Pharmacy (PharmD) or B.Pharm'],
    certifications: ['Pharmacy licensure'],
    courses: [course('Introduction to Pharmacology', 'Coursera', 'pharmacology'), course('Drug Discovery', 'edX', 'pharmacology')],
  },
  {
    name: 'Philosopher',
    summary: 'Examines fundamental questions of knowledge, values and existence.',
    description: 'Philosophers analyze concepts and arguments about reality, ethics and reason, writing and teaching about complex ideas.',
    outlook: 'Academic demand',
    workEnvironment: 'Universities and research / writing settings.',
    salary: [45000, 68000, 110000],
    intelligences: [INTEL.ling, INTEL.intra, INTEL.logic],
    skills: ['Logical reasoning', 'Critical analysis', 'Argumentation', 'Academic writing', 'Abstraction'],
    responsibilities: ['Analyze philosophical questions', 'Construct and critique arguments', 'Write and publish work', 'Teach and lead discussions'],
    degrees: ['PhD in Philosophy'],
    certifications: ['Academic research training'],
    courses: [course('Introduction to Philosophy', 'Coursera', 'philosophy'), course('Logic & Critical Thinking', 'edX', 'logic critical thinking')],
  },
  {
    name: 'Physical Therapist',
    summary: 'Restores movement and function through therapeutic exercise and treatment.',
    description: 'Physical therapists assess and treat movement disorders, designing rehabilitation programs to restore mobility and reduce pain.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Clinics, hospitals and rehabilitation centers.',
    salary: [70000, 92000, 120000],
    intelligences: [INTEL.body, INTEL.inter, INTEL.logic],
    skills: ['Movement assessment', 'Rehabilitation', 'Manual therapy', 'Patient motivation', 'Anatomy'],
    responsibilities: ['Assess movement and function', 'Design rehab programs', 'Guide therapeutic exercise', 'Track and adjust treatment'],
    degrees: ['Doctor of Physical Therapy (DPT)'],
    certifications: ['PT licensure'],
    courses: [course('Anatomy & Physiology', 'Coursera', 'anatomy physiology'), course('Rehabilitation Science', 'edX', 'rehabilitation')],
  },
  {
    name: 'Physician',
    summary: 'Diagnoses and treats illness and injury as a licensed medical doctor.',
    description: 'Physicians evaluate patients, diagnose conditions and direct treatment, often specializing in a field of medicine.',
    outlook: 'Strong demand',
    workEnvironment: 'Hospitals, clinics and private practice.',
    salary: [180000, 250000, 400000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.intra],
    skills: ['Clinical diagnosis', 'Medical knowledge', 'Decision making', 'Patient communication', 'Empathy'],
    responsibilities: ['Examine and diagnose patients', 'Order and interpret tests', 'Prescribe and manage treatment', 'Coordinate specialist care'],
    degrees: ['Medical degree (MD / MBBS) + residency'],
    certifications: ['Medical licensure', 'Specialty board certification'],
    courses: [course('Clinical Diagnostics', 'Coursera', 'clinical medicine'), course('Human Anatomy', 'edX', 'human anatomy')],
  },
  {
    name: 'Physicist',
    summary: 'Studies matter, energy and the fundamental laws of nature.',
    description: 'Physicists investigate physical phenomena through theory and experiment, advancing understanding from particles to the cosmos.',
    outlook: 'Steady research demand',
    workEnvironment: 'Universities, national labs and R&D settings.',
    salary: [70000, 115000, 175000],
    intelligences: [INTEL.logic, INTEL.spatial, INTEL.intra],
    skills: ['Mathematical modeling', 'Experimentation', 'Data analysis', 'Programming', 'Scientific writing'],
    responsibilities: ['Develop and test physical theories', 'Design and run experiments', 'Analyze experimental data', 'Publish and present findings'],
    degrees: ['PhD in Physics'],
    certifications: ['Research fellowships'],
    courses: [course('Introduction to Physics', 'edX', 'physics'), course('Quantum Mechanics', 'Coursera', 'quantum mechanics')],
  },
  {
    name: 'Pilot',
    summary: 'Operates aircraft to transport passengers or cargo safely.',
    description: 'Pilots fly and navigate aircraft, managing systems, weather and procedures to ensure safe flights.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Cockpits; irregular schedules and travel.',
    salary: [70000, 130000, 250000],
    intelligences: [INTEL.spatial, INTEL.logic, INTEL.body],
    skills: ['Flight operations', 'Navigation', 'Situational awareness', 'Decision making', 'Communication'],
    responsibilities: ['Plan and conduct flights', 'Operate aircraft systems', 'Monitor weather and navigation', 'Ensure passenger and crew safety'],
    degrees: ['Commercial pilot training'],
    certifications: ['Commercial Pilot License (CPL) / ATPL'],
    courses: [course('Aviation Fundamentals', 'Coursera', 'aviation'), course('Aerodynamics Basics', 'edX', 'aerodynamics')],
  },
  {
    name: 'Poet',
    summary: 'Crafts verse and poetic language to evoke emotion and meaning.',
    description: 'Poets compose original poetry, experimenting with language, rhythm and imagery to express ideas and feeling.',
    outlook: 'Project-based',
    workEnvironment: 'Independent writing; readings and publications.',
    salary: [25000, 45000, 80000],
    intelligences: [INTEL.ling, INTEL.intra, INTEL.music],
    skills: ['Creative writing', 'Imagery & metaphor', 'Rhythm', 'Editing', 'Self-reflection'],
    responsibilities: ['Write and revise poetry', 'Develop a voice and style', 'Submit work for publication', 'Perform at readings'],
    degrees: ["Bachelor's in Creative Writing or English"],
    certifications: ['Writing workshops'],
    courses: [course('Sharpened Visions: Poetry', 'Coursera', 'poetry writing'), course('Creative Writing', 'edX', 'creative writing')],
  },
  {
    name: 'Police Force (Spies, CBI officials, CID, Detectives)',
    summary: 'Maintains law and order and investigates crime.',
    description: 'Police and investigative officers enforce laws, investigate crimes and protect communities, combining analysis, discipline and public service.',
    outlook: 'Steady recruitment',
    workEnvironment: 'Stations, field patrols and investigation units.',
    salary: [40000, 62000, 110000],
    intelligences: [INTEL.inter, INTEL.logic, INTEL.body],
    skills: ['Investigation', 'Situational awareness', 'Critical thinking', 'Communication', 'Physical fitness'],
    responsibilities: ['Patrol and maintain order', 'Investigate crimes and gather evidence', 'Interview witnesses and suspects', 'Prepare case reports'],
    degrees: ["Bachelor's (criminology/related) + academy training"],
    certifications: ['Police academy certification'],
    courses: [course('Criminal Justice', 'edX', 'criminal justice'), course('Forensic Science', 'Coursera', 'forensic science')],
  },
  {
    name: 'Politician',
    summary: 'Represents constituents and shapes public policy and governance.',
    description: 'Politicians develop and advocate policy, represent communities and build consensus to lead public decision-making.',
    outlook: 'Election-based',
    workEnvironment: 'Legislatures, campaigns and public engagements.',
    salary: [50000, 90000, 200000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.intra],
    skills: ['Public speaking', 'Negotiation', 'Policy analysis', 'Persuasion', 'Coalition building'],
    responsibilities: ['Represent constituents', 'Develop and debate policy', 'Build consensus and coalitions', 'Communicate with the public'],
    degrees: ["Bachelor's in Political Science, Law or related"],
    certifications: ['Public administration programs'],
    courses: [course('Introduction to Political Science', 'edX', 'political science'), course('Public Policy', 'Coursera', 'public policy')],
  },
  {
    name: 'Pre Primary Teacher (2020 NEP and Mental Health)',
    summary: 'Teaches and nurtures early-childhood learners through play-based learning.',
    description: 'Pre-primary teachers create safe, engaging environments for young children, supporting early development, learning and mental well-being.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Preschools and early-childhood centers.',
    salary: [30000, 45000, 70000],
    intelligences: [INTEL.inter, INTEL.intra, INTEL.ling],
    skills: ['Early-childhood pedagogy', 'Patience', 'Creativity', 'Observation', 'Emotional support'],
    responsibilities: ['Plan play-based activities', 'Support early learning and development', 'Observe and nurture well-being', 'Communicate with parents'],
    degrees: ['Diploma / Bachelor in Early Childhood Education'],
    certifications: ['ECCE certification'],
    courses: [course('Early Childhood Education', 'Coursera', 'early childhood education'), course('Child Development', 'edX', 'child development')],
  },
  {
    name: 'Primary Teacher',
    summary: 'Educates young students across core subjects in primary school.',
    description: 'Primary teachers deliver foundational education across subjects, fostering literacy, numeracy and social development.',
    outlook: 'Stable demand',
    workEnvironment: 'Primary schools and classrooms.',
    salary: [35000, 52000, 78000],
    intelligences: [INTEL.ling, INTEL.inter, INTEL.intra],
    skills: ['Lesson planning', 'Classroom management', 'Communication', 'Patience', 'Assessment'],
    responsibilities: ['Plan and teach lessons', 'Manage the classroom', 'Assess student progress', 'Support diverse learners'],
    degrees: ["Bachelor's in Education (B.Ed) or Elementary Education"],
    certifications: ['Teaching license'],
    courses: [course('Foundations of Teaching', 'Coursera', 'teaching'), course('Classroom Management', 'Udemy', 'classroom management')],
  },
  {
    name: 'Psychologist',
    summary: 'Studies cognitive, emotional and social behavior to support mental health.',
    description: 'Psychologists assess and treat behavioral and emotional issues, applying research and therapy to help individuals and groups.',
    outlook: 'Growing field',
    workEnvironment: 'Clinics, hospitals, schools and research labs.',
    salary: [60000, 90000, 130000],
    intelligences: [INTEL.inter, INTEL.intra, INTEL.ling],
    skills: ['Behavioral assessment', 'Active listening', 'Diagnosis', 'Therapeutic techniques', 'Empathy'],
    responsibilities: ['Conduct psychological assessments', 'Provide counseling and therapy', 'Formulate behavioral diagnostics', 'Collaborate on mental health programs'],
    degrees: ["Master's or PhD in Psychology"],
    certifications: ['State psychology license'],
    courses: [course('Introduction to Psychology', 'Coursera', 'psychology'), course('Clinical Psychology', 'edX', 'clinical psychology')],
  },
  {
    name: 'Receptionist',
    summary: 'Manages front-desk operations, greeting visitors and handling enquiries.',
    description: 'Receptionists are the first point of contact for an organization, managing calls, scheduling and visitor coordination.',
    outlook: 'Stable demand',
    workEnvironment: 'Office and front-desk settings.',
    salary: [28000, 38000, 55000],
    intelligences: [INTEL.inter, INTEL.ling, INTEL.intra],
    skills: ['Customer service', 'Communication', 'Organization', 'Scheduling', 'Multitasking'],
    responsibilities: ['Greet and direct visitors', 'Manage calls and enquiries', 'Schedule appointments', 'Maintain front-desk records'],
    degrees: ['High school diploma / office administration'],
    certifications: ['Office administration certificate'],
    courses: [course('Customer Service Skills', 'Udemy', 'customer service'), course('Business Communication', 'Coursera', 'business communication')],
  },
  {
    name: 'Recording engineer',
    summary: 'Captures, mixes and produces audio recordings in studios.',
    description: 'Recording engineers operate equipment to record, edit and mix music and sound, balancing technical skill with a musical ear.',
    outlook: 'Project-based demand',
    workEnvironment: 'Recording studios and live venues.',
    salary: [35000, 55000, 95000],
    intelligences: [INTEL.music, INTEL.logic, INTEL.spatial],
    skills: ['Audio recording', 'Mixing & mastering', 'DAW software', 'Acoustics', 'Attention to detail'],
    responsibilities: ['Set up and operate recording gear', 'Record and edit audio', 'Mix and master tracks', 'Collaborate with artists and producers'],
    degrees: ['Diploma / Bachelor in Audio Engineering'],
    certifications: ['Pro Tools / audio certifications'],
    courses: [course('Music Production', 'Coursera', 'music production'), course('Audio Engineering', 'Udemy', 'audio engineering')],
  },
  {
    name: 'Research analyst',
    summary: 'Gathers and analyzes data to produce insights and recommendations.',
    description: 'Research analysts collect, interpret and report on data and trends to support decisions in finance, markets or industry.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Offices and research teams; data-driven.',
    salary: [50000, 75000, 120000],
    intelligences: [INTEL.logic, INTEL.ling, INTEL.intra],
    skills: ['Data analysis', 'Statistical methods', 'Research design', 'Reporting', 'Critical thinking'],
    responsibilities: ['Collect and clean data', 'Analyze trends and patterns', 'Build reports and dashboards', 'Communicate insights to stakeholders'],
    degrees: ["Bachelor's in Economics, Statistics or Business"],
    certifications: ['Data analytics certifications'],
    courses: [course('Data Analysis', 'Coursera', 'data analysis'), course('Research Methods', 'edX', 'research methods')],
  },
  {
    name: 'Sales Representative',
    summary: 'Sells products and services and builds customer relationships.',
    description: 'Sales representatives identify prospects, present solutions and close deals, nurturing relationships to drive revenue.',
    outlook: 'Strong demand',
    workEnvironment: 'Field, office and remote; client-facing.',
    salary: [40000, 65000, 130000],
    intelligences: [INTEL.inter, INTEL.ling, INTEL.intra],
    skills: ['Persuasion', 'Relationship building', 'Negotiation', 'Product knowledge', 'Resilience'],
    responsibilities: ['Identify and qualify prospects', 'Present products and solutions', 'Negotiate and close deals', 'Maintain client relationships'],
    degrees: ["Bachelor's in Business or related (varies)"],
    certifications: ['Sales methodology certifications'],
    courses: [course('Sales Training', 'Udemy', 'sales training'), course('Successful Negotiation', 'Coursera', 'negotiation')],
  },
  {
    name: 'Social Worker',
    summary: 'Supports individuals and communities facing social and personal challenges.',
    description: 'Social workers assess needs and connect people with resources and support, advocating for well-being and social justice.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Agencies, schools, hospitals and communities.',
    salary: [40000, 55000, 80000],
    intelligences: [INTEL.inter, INTEL.intra, INTEL.ling],
    skills: ['Case management', 'Empathy', 'Advocacy', 'Active listening', 'Resourcefulness'],
    responsibilities: ['Assess client needs', 'Connect clients with resources', 'Advocate for vulnerable groups', 'Maintain case records'],
    degrees: ["Bachelor's or Master's in Social Work (BSW/MSW)"],
    certifications: ['Social work licensure'],
    courses: [course('Introduction to Social Work', 'edX', 'social work'), course('Community Wellbeing', 'Coursera', 'community health')],
  },
  {
    name: 'Sound editor',
    summary: 'Edits and designs sound for film, television and media.',
    description: 'Sound editors assemble, clean and design audio — dialogue, effects and ambience — to support storytelling in media.',
    outlook: 'Project-based demand',
    workEnvironment: 'Post-production studios and editing suites.',
    salary: [40000, 62000, 100000],
    intelligences: [INTEL.music, INTEL.spatial, INTEL.logic],
    skills: ['Sound design', 'Audio editing', 'DAW software', 'Foley', 'Attention to detail'],
    responsibilities: ['Edit dialogue and effects', 'Design and layer soundscapes', 'Sync audio to picture', 'Collaborate with directors and mixers'],
    degrees: ['Diploma / Bachelor in Sound Design or Audio'],
    certifications: ['Pro Tools certification'],
    courses: [course('Sound Design', 'Udemy', 'sound design'), course('Audio Production', 'Coursera', 'audio production')],
  },
  {
    name: 'Stock Broker',
    summary: 'Buys and sells securities on behalf of clients and advises on investments.',
    description: 'Stock brokers execute trades, monitor markets and advise clients on equities and investment strategy.',
    outlook: 'Competitive demand',
    workEnvironment: 'Trading floors, brokerages; fast-paced.',
    salary: [50000, 90000, 200000],
    intelligences: [INTEL.logic, INTEL.inter, INTEL.intra],
    skills: ['Market analysis', 'Trading', 'Risk management', 'Client relations', 'Decision speed'],
    responsibilities: ['Execute buy and sell orders', 'Monitor market movements', 'Advise clients on investments', 'Manage trading risk'],
    degrees: ["Bachelor's in Finance, Economics or Business"],
    certifications: ['Series 7 / brokerage licensing'],
    courses: [course('Financial Markets', 'Coursera', 'financial markets'), course('Trading Basics', 'Udemy', 'stock trading')],
  },
  {
    name: 'Technician',
    summary: 'Installs, maintains and repairs technical equipment and systems.',
    description: 'Technicians apply practical and technical skills to set up, troubleshoot and service equipment across industries.',
    outlook: 'Stable demand',
    workEnvironment: 'Workshops, field sites and facilities.',
    salary: [35000, 52000, 80000],
    intelligences: [INTEL.body, INTEL.logic, INTEL.spatial],
    skills: ['Troubleshooting', 'Equipment maintenance', 'Technical reading', 'Problem solving', 'Safety procedures'],
    responsibilities: ['Install and configure equipment', 'Diagnose and repair faults', 'Perform preventive maintenance', 'Document service work'],
    degrees: ['Technical / vocational diploma'],
    certifications: ['Industry technician certifications'],
    courses: [course('Technical Support Fundamentals', 'Coursera', 'technical support'), course('Electronics Basics', 'Udemy', 'electronics')],
  },
  {
    name: 'Veterinarian',
    summary: 'Diagnoses and treats the health of animals.',
    description: 'Veterinarians provide medical care to animals, performing diagnoses, surgery and preventive care for pets, livestock and wildlife.',
    outlook: 'Strong growth outlook',
    workEnvironment: 'Clinics, farms and animal hospitals.',
    salary: [70000, 100000, 160000],
    intelligences: [INTEL.nature, INTEL.logic, INTEL.inter],
    skills: ['Animal diagnosis', 'Surgery', 'Patient handling', 'Empathy', 'Medical knowledge'],
    responsibilities: ['Examine and diagnose animals', 'Perform treatment and surgery', 'Advise owners on care', 'Administer vaccinations'],
    degrees: ['Doctor of Veterinary Medicine (DVM/BVSc)'],
    certifications: ['Veterinary licensure'],
    courses: [course('Animal Health & Welfare', 'edX', 'animal health'), course('Veterinary Science Basics', 'Coursera', 'veterinary science')],
  },
  {
    name: 'Writer',
    summary: 'Develops original written content for books, articles or media.',
    description: 'Writers craft and refine content across genres, combining linguistic skill, research and a distinctive voice.',
    outlook: 'Stable demand',
    workEnvironment: 'Independent, publishing and remote editorial settings.',
    salary: [40000, 60000, 100000],
    intelligences: [INTEL.ling, INTEL.intra, INTEL.inter],
    skills: ['Creative writing', 'Storytelling', 'Research', 'Editing', 'Audience targeting'],
    responsibilities: ['Draft and edit original content', 'Research supporting material', 'Revise from editorial feedback', 'Collaborate with editors and publishers'],
    degrees: ["Bachelor's in Creative Writing, English or Journalism"],
    certifications: ['Writing workshops'],
    courses: [course('Creative Writing Specialization', 'Coursera', 'creative writing'), course('Writing for the Web', 'Udemy', 'web writing')],
  },
]

export default careers
